spring.application.name=database-api
spring.datasource.url=jdbc:postgresql://localhost:5432/naukri-db
spring.datasource.username=postgres
spring.datasource.password=Sunil@10102000
spring.jpa.hibernate.ddl-auto=update

